import { Work } from '@/app/types';

const works: Work[] = [
  {
    num: 1,
    id: "work5",
    title: "generative splatter paintings",
    subtitle1: "digital representation of Pollock's Splatter Paintings",
    category: "developing",
    type: "generative art",
    description: "as a final degree project I developed an interactive exhibition where people could interact with an interface and create a Pollock Splatter Painting with complete freedom.",
    roles: "concept, developing, installation, analysis",
    date: "2022-2023",
    client: "uni",
    short_link: "trailer video",
    link: "https://www.youtube.com/watch?v=nQFbTK_jLtU",
    image1_alt: "",
    image2_alt: "",
    image3_alt: "",
    image4_alt: "",
    image5_alt: "",
    image6_alt: "",
    image7_alt: "",
  },
  {
    num: 2,
    id: "work14",
    title: "funerary services platform",
    subtitle1: "multidomain e-commerce and services platform with headless CMS",
    category: "developing",
    type: "full stack",
    description:
      "A multidomain Next.js platform for a funerary services company where each tanatory operates under its own domain — domain-based routing drives all content and logic. Directus acts as the headless CMS, letting the client manage tables and content without touching code. The platform includes a full e-commerce shop that pulls products from a third-party integration and writes purchases back to the same system. Stripe handles payment processing and a Telegram bot automatically routes all form submissions to the internal work group. Built with a single codebase serving multiple branded domains.",
    roles: "full stack, architecture, integrations",
    date: "2025",
    client: "work",
    short_link: "pfb-serveisfuneraris.com",
    link: "https://pfb-serveisfuneraris.com/",
    image1_alt: "funerary services homepage",
    image2_alt: "shop page",
    image3_alt: "cookies banner",
    image4_alt: "navigation menu",
    image5_alt: "services page",
    image6_alt: "shopping cart",
    image7_alt: "checkout process",
    imageExt: "png",
  },
  {
    num: 3,
    id: "work15",
    title: "stroke assessment toolkit",
    subtitle1: "mobile apps and clinical dashboard for ictus case management",
    category: "developing",
    type: "mobile + web",
    description:
      "A suite of tools for stroke response and clinical case management. The public-facing Race Scale app lets emergency responders perform standardised stroke severity assessments in the field. The companion Race+ app extends this to full case lifecycle management: creating and assigning ictus cases to medical centres, performing assessments, and tracking outcomes. A web dashboard provides hospital administrators and superadmins with multi-organisation views, user management, and role-based access control.",
    roles: "full stack, architecture, mobile",
    date: "2024 - present",
    client: "work",
    short_link: "",
    link: "",
    image1_alt: "race scale app home",
    image2_alt: "race scale assessment screen",
    image3_alt: "race+ case list",
    image4_alt: "race+ new case form",
    image5_alt: "clinical dashboard overview",
    image6_alt: "multi-org superadmin view",
    image7_alt: "user and role management",
    imageExt: "png",
  }
];

export default works;
