const works = [
  {
    num: 1,
    id: "work1",
    title: "frontend project",
    subtitle1: "subtitle from uni project 1",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "developing",
    type: "frontend",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
    image7_alt: "alt for image 7",
  },
  {
    num: 2,
    id: "work2",
    title: "backend project",
    subtitle1: "subtitle from uni project 2",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "developing",
    type: "backend",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
  },
  {
    num: 3,
    id: "work3",
    title: "branding project",
    subtitle1: "subtitle from uni project 3",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "design",
    type: "branding",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
  },
  {
    num: 4,
    id: "work4",
    title: "graphic design project",
    subtitle1: "subtitle from uni project 4",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "design",
    type: "graphic design",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
  },
  {
    num: 5,
    id: "work5",
    title: "3d project",
    subtitle1: "subtitle from uni project 5",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "other",
    type: "3d",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
  },
  {
    num: 6,
    id: "work6",
    title: "social media project",
    subtitle1: "subtitle from uni project 6",
    subtitle2: "cool sentence to start part 2",
    subtitle3: "cool sentence to start part 3",
    category: "other",
    type: "social media",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    description2:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    description3:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    roles: "design, modelling, photography",
    date: "2022",
    client: "personal",
    image1_alt: "alt for image 1",
    image2_alt: "alt for image 2",
    image3_alt: "alt for image 3",
    image4_alt: "alt for image 4",
    image5_alt: "alt for image 5",
    image6_alt: "alt for image 6",
  },
];

export default works;
